---
- name: Install required packages
  package:
    name: "{{ packages_base | union(packages_additional) | unique }}"
    state: present
  register: installed_package
  until: installed_package is succeeded
  become: True

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg }}"
  become: True

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    validate_certs: True
  become: True
